document.addEventListener("DOMContentLoaded",function(){
    //Render skills
    renderSkills();
    initModal();
    initContactValidation();
    initThemeToggle();
    renderProjects(projectexpand);
    renderEducations();
    initScrollProgress();
    initScrollSpy();
    initBackToTop();
    initProjectFilters();
    initProjectCount();
    initProjectSorting();
    initProjectExpand();
    initGeolocationMessage();
    initDynamicGreeting();
    showRecent();
})